---
title: "Virginia Election Project"
author: "putyournamehere"
execute:
  echo: true
format:
  html:
    self-contained: true
    code-tools: true
---


```{r setup, include=FALSE, warning=FALSE, message=FALSE}


library(tidyverse)
library(janitor)
library(httr)
library(jsonlite)
library(kableExtra)
library(here)
options(scipen = 999)
options(stringsAsFactors = FALSE)


#load saved joined data file from previous script
joined_vacomparison <- readRDS(here("processed_data", "joined_vacomparison.rds"))



```


# Comparing Virgnia Gov vs. Prez



```{r}

head(joined_vacomparison)


```

```{r}

joined_vacomparison = joined_vacomparison %>% 
  mutate(YoungkinADV = pct_youngkin - trump_pct)
head(joined_vacomparison)



```
```{r}

TOP5 <- joined_vacomparison %>% 
  arrange(desc(YoungkinADV)) %>% 
  slice(1:5)

ggplot(TOP5, aes(x = locality, y = YoungkinADV)) +
  geom_bar(stat="identity", fill="coral")+
  scale_x_discrete(guide = guide_axis(n.dodge=3))

```
```{r}

YOUNGKIN_5 <- joined_vacomparison %>% 
  arrange(desc(pct_youngkin)) %>% 
  slice(1:5)

ggplot(YOUNGKIN_5, aes(x = locality, y = pct_youngkin)) +
  geom_bar(stat="identity", fill="darkred")+
  scale_x_discrete(guide = guide_axis(n.dodge=3))
```


```{r}

MCAULIFFE_5 <- joined_vacomparison %>% 
  arrange(desc(pct_mcauliffe)) %>% 
  slice(1:5)

ggplot(MCAULIFFE_5, aes(x = locality, y = pct_mcauliffe)) +
  geom_bar(stat="identity", fill="steelblue")+
  scale_x_discrete(guide = guide_axis(n.dodge=3))

```


```{r}

joined_vacomparison = joined_vacomparison %>% 
  mutate(biden_adv = biden_pct - pct_mcauliffe)

BIDEN_ADV <- joined_vacomparison %>% 
  arrange(desc(biden_adv)) %>% 
  slice(1:5)

ggplot(BIDEN_ADV, aes(x = locality, y = biden_adv)) +
  geom_bar(stat="identity", fill="navy")+
  scale_x_discrete(guide = guide_axis(n.dodge=3))

```


```{r}

joined_vacomparison = joined_vacomparison %>% 
  mutate(biden20_adv = biden_pct - trump_pct)

BIDEN20_ADV <- joined_vacomparison %>% 
  arrange(desc(biden20_adv)) %>% 
  slice(1:5)

ggplot(BIDEN20_ADV, aes(x = locality, y = biden20_adv)) +
  geom_bar(stat="identity", fill="purple")+
  scale_x_discrete(guide = guide_axis(n.dodge=3))

```


```{r}

joined_vacomparison = joined_vacomparison %>% 
  mutate(trump20_adv = trump_pct - biden_pct)

TRUMP20_ADV <- joined_vacomparison %>% 
  arrange(desc(trump20_adv)) %>% 
  slice(1:5)

ggplot(TRUMP20_ADV, aes(x = locality, y = trump20_adv)) +
  geom_bar(stat="identity", fill="orange")+
  scale_x_discrete(guide = guide_axis(n.dodge=3))

```





